name: vgyupload
description: A simple command-line application to upload to vgy.me
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.2.3

# Add regular dependencies here.
dependencies:
  path: ^1.9.0
  http: ^1.1.2

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0